apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-nginx
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      name: loadbalancer-nginx-http
    - port: 443
      protocol: TCP
      name: loadbalancer-nginx-https
    - port: 22
      protocol: TCP
      name: loadbalancer-nginx-ssh
  selector:
    app: ft_services
    tier: nginx