apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      protocol: TCP
  selector:
    app: ft_services
    tier: phpmyadmin