apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
    - port: 5050
      protocol: TCP
  selector:
    app: ft_services
    tier: wordpress