apiVersion: apps/v1
kind: Deployment # 생성하고자 하는 자원의 종류 (디플로이먼트)
metadata:
  name: influxdb # Deployment Name
spec:
  replicas: 1 # pod 복제본 개수
  selector: # 구분되는 조건
    matchLabels:
      app: ft_services # 라벨1 (앱 이름)
      tier: influxdb # 라벨2
  template: # 생성할 pod들의 템플릿
    metadata:
      labels:
        app: ft_services # 라벨1 (앱 이름)
        tier: influxdb # 라벨2
    spec:
      containers:
        - name: influxdb # 컨테이너 이름
          image: ft_services/influxdb:0.3
          volumeMounts: # 퍼시스턴스 볼륨 접근
          - name: influxdb-data-v
            mountPath: /var/lib/influxdb
      volumes:
        - name: influxdb-data-v
          persistentVolumeClaim:
            claimName: influxdb-data